name: Run packer build

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TEST_ENV: ${{ secrets.TEST_ENV }}
  TEST_ENV_2: "Testing env 2"

on:
  # pull_request:
  pull_request_target:
    types: [opened,reopened]
    branches: [ main ]
    
jobs:
  packer_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test variables
        run: |
            echo env.AWS_ACCESS_KEY_ID
            echo env.AWS_SECRET_ACCESS_KEY
            echo env.TEST_ENV
            echo env.TEST_ENV_2
            printenv
    
      - name: Packer build
        uses: riznob/packer-build-action@v1.1
        with:
          templateFile: 'packer-template.json'
          varFile: 'packer-vars.json'
          workingDir: '.'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          AWS_SOURCE_AMI: ${{ secrets.AWS_SOURCE_AMI }}
          AWS_PROD_ACCOUNT_ID: ${{ secrets.AWS_PROD_ACCOUNT_ID }}
